---
title: "Wage Share and Regional Inequality in Switzerland"
author: "Celâl Güney"
format: 
  html:
    toc: true
editor: visual
categories: [Income inequality]
draft: true
---

```{r}
#| echo: false
#| warning: false
#| message: false

rm(list = ls())
library(rnaturalearth)
library(tidyverse)
library(sf)
library(BFS)
library(viridis)
library(patchwork)
library(leaflet)
library(mapview)
library(readxl)
```

## Introduction

```{r}
#| echo: false
#| warning: false
#| message: false

ULC <- read_csv("data_inequality/ULC_ameco.csv")

ULC <- 
  ULC %>% 
  pivot_longer(cols = 2:8, names_to = "Country", values_to = "Wage_share")

wageShare_ameco <- read_csv("data_inequality/wageShare_ameco.csv")

wageShare_ameco <- 
  wageShare_ameco %>% 
  pivot_longer(cols = 2:9, values_to = "Wage_share", names_to = "Country")



library(ggrepel)

wageShare_ameco %>%
  filter(period %in% c(1991:2024) & Country != "Norway") %>%
  ggplot(aes(x = period, y = Wage_share, group = Country)) +
  
  geom_line(aes(color = ifelse(Country == "Switzerland", "Switzerland", "Other")),
            size = 1) + 
  
    scale_color_manual(values = c("Switzerland" = "red", "Other" = "grey")) +
  
  geom_text_repel(data = wageShare_ameco %>%
                    filter(period == max(period) & Country != "Norway" & Country != "Switzerland"),
                  aes(label = Country),
                  nudge_x = 0.5,  
                  hjust = 0,      
                  direction = "y", 
                  size = 3) +
  
  geom_text_repel(data = wageShare_ameco %>%
                    filter(period == max(period) & Country == "Switzerland"),
                  aes(label = Country),
                  nudge_x = 0.5,  
                  nudge_y = 0.5,  
                  hjust = 0,      
                  color = "red",  
                  size = 3,       
                  fontface = "bold") +  
  
  labs(title = "Wage Share by Country (1991-2024)",
       x = "", y = "Wage Share in %") +
  theme_minimal() +
  theme(legend.position = "none")  




```

```{r siegenthaler}
#| echo: false
#| warning: false
#| message: false

siegen2024 <- read_excel("data_inequality/siegenthaler_etal_2024.xlsx", 
    skip = 1)

siegen2024$wage_shareCH = siegen2024$`Reales Arbeitnehmerentgelt (Mio. CHF 2005)`/siegen2024$`Reales BIP (Mio. CHF 2005)`
wage_shareCH_ameco = wageShare_ameco$Wage_share[wageShare_ameco$Country == "Switzerland"]
wage_shareCH_ameco = as.numeric(wage_shareCH_ameco)


siegen2024 %>% 
  filter() %>% 
  ggplot()+
  aes(x = Jahr, y = wage_shareCH*100)+
  geom_line()
```

```{r}
#| echo: false
#| warning: false
#| message: false

AFC_data_CH = read.csv("AFC_data_CH.csv")


AFC_data_CH %>% 
  ggplot()+
  aes(x = year, y = gini_reinka)+
  geom_point()+
  geom_line()+
  theme_minimal()+
  labs(x = "", y = "Gini of net equivalent disposable income")
```

```{r}
#| echo: false
#| warning: false
#| message: false

switzerland = bfs_get_base_maps(geom = "kant")
AFC_data_canton <- read_csv("AFC_data_canton.csv") %>% 
  rename("id" = ktnr)

map_data_ch = switzerland %>% 
  left_join(AFC_data_canton, by = "id")


quantile_gini = quantile(map_data_ch$gini_reinka[map_data_ch$year == 2019], probs = seq(0, 1, by = 0.2))
map_data_ch$breaks_gini = cut(map_data_ch$gini_reinka,
                  breaks = quantile_gini)

map_data_ch %>% 
  filter(year == 2019) %>% 
  mapview(zcol = "gini_reinka")
```

```{r}
#| echo: false
#| warning: false
#| message: false

AFC_data_canton %>% 
  ggplot()+
  aes(x = year, y = gini_reinka)+
  geom_line(size = 0.8)+
  facet_wrap(~ktname)+
  theme_minimal()+
  theme(axis.text.x = element_text(angle = 70, vjust = 0.5, hjust=1))+
  labs(x = "", y = "Gini of net disposable equivalent income")
  

```

```{r}
#| echo: false
#| warning: false
#| message: false

library(ggrepel)

swiss_communes = bfs_get_base_maps(geom = "polg")
afc_data_communes = read.csv("AFC_data_communes.csv") %>% 
  rename("id" = gdenr)

map_data_communes = swiss_communes %>% 
  left_join(afc_data_communes, by = "id")

map_data_communes %>%
  filter(id %in% c(6601:6645) & year == 2020) %>%
  mutate(label_color = case_when(
    gini_reinka < 0.7 ~ "black",
    gini_reinka >= 0.7 ~ "white"
  )) %>%
  ggplot() +
  geom_sf(aes(fill = gini_reinka)) +
  scale_fill_viridis(option = 1, direction = -1) +
  theme_void() +
  geom_sf_text(aes(label = name, color = label_color), size = 3) +
  scale_color_manual(values = c("black", "white"), guide = "none")


```

```{r}
#| echo: false
#| warning: false
#| message: false
#| eval: false
#| include: false

map =
map_data_ch %>% 
  filter(year == 2019) %>% 
  ggplot()+
  geom_sf(aes(fill = breaks_gini))+
  theme_void()+
  scale_fill_viridis(option = "A", discrete = TRUE, direction = -1,
                     guide = guide_legend(position = "bottom",
                                          label.position = "bottom",
                                          nrow = 2),
                     name = "")+
  labs(title = "Gini coefficient of net equivalent disposable income (2019)",
       caption = "Data source: Swiss Federal Tax Administration")



AFC_data_canton$breaks_gini = cut(AFC_data_canton$gini_reinka,
                  breaks = quantile_gini)

barplot = 
AFC_data_canton %>% 
  filter(year == 2019) %>% 
  ggplot()+
  aes(y = reorder(ktname, gini_reinka), x = gini_reinka, fill = breaks_gini)+
  geom_col()+
  labs(x = "", y = "")+
  theme_minimal()+
  scale_fill_viridis(option = "A", discrete = TRUE, direction = -1)+
  theme(legend.position = "none")


map+
  inset_element(barplot, -0.18, 0.1, 0.1, 1)
```
