---
title: "Reproducing WPID's results"
format: html
editor: visual
execute: 
  freeze: true
draft: true
date: "2 July 2023"
categories: [Political Economy]
---

## Switzerland

To analyze the evolution of political cleavages, [Piketty et al (2021)](https://wid.world/wp-content/uploads/2021/05/WorldInequalityLab_WP2021_15_PoliticalCleavages_WesternDemocracies.pdf) compiled datasets covering a lot of countries.

```{r}
#| warning: false
#| message: false
#| echo: false
#| eval: false

rm(list = ls())
library(tidyverse)
library(nnet)
library(haven)
library(sjlabelled)
library(knitr)
library(gridExtra)
library(stargazer)
library(marginaleffects)
library(arm)
library(plot3logit)
library(RColorBrewer)
library(DescTools)
library(splitstackshape)
library(lme4)
library(brms)
setwd("F:/myblog/Posts/Reproducing WPID's results")
```

```{r}
#| warning: false
#| message: false
#| echo: false
#| eval: false
chinc <- read_dta("ch-inc.dta")
names(chinc)
```

```{r}
#| warning: false
#| message: false
#| echo: false
#| eval: false
unique(chinc$year)
chinc %>% arrange(id)
```

```{r}
#| warning: false
#| message: false
#| echo: false
#| eval: false
data2015  <- 
chinc %>% 
  filter(year == 2015 )


summary(glm(voteleft ~ dinc_10, family = binomial(link = "logit"), data = data2015))

```
