---
title: "Social blocs and political cleavages in Switzerland"
format: html
editor: visual
execute: 
  freeze: true
categories: [Political Economy, Statistics]
author: "Celâl Güney"
date: "9 July 2023"
draft: true
---

```{r set up}
#| echo: false
#| warning: false
#| message: false
rm(list = ls())
library(haven)
library(sjlabelled)
library(tidyverse)
library(viridis)
library(stargazer)
library(gtsummary)
library(gt)
library(brms)
library(ggrepel)
library(cowplot)
library(ggpubr)
library(lme4)
library(prediction)
library(marginaleffects)
library(ggeffects)
library(ordinal)
library(broom)

theme_set(theme_bw())
```

```{r loading data}
#| echo: false
#| warning: false
#| message: false
vox <- read_sav("F:/mapec/Master THESIS/projectB_politicalecon/data/vox/vox_cumulative_dataset/688_VoxIt_Data_CumulatedFile_Projets_15_121_F.sav")

```


```{r party dummies and income variable}
#| echo: false
#| warning: false
#| message: false
vox <- vox %>% 
  mutate(income = if_else(revenu == 1 & is.na(nivmena), 4,
                          if_else(revenu == 2 & is.na(nivmena), 3,
                                  if_else(revenu %in% c(3,4) & is.na(nivmena), 2,
                                          if_else(revenu == 5 & is.na(nivmena), 1,
                                                  if_else(is.na(revenu) & annee <= 1993, nivmena, NA))))))

         
vox$income <- ifelse(vox$income == 4, 1,
                    ifelse(vox$income == 3, 2,
                        ifelse(vox$income == 2, 3,
                          ifelse(vox$income == 1, 4, NA))))

vox$pss <- ifelse(vox$p02 == 12, 1,
                  ifelse(is.na(vox$p02), NA, 0))

vox$udc <- ifelse(vox$p02 == 13, 1,
                  ifelse(is.na(vox$p02), NA, 0))

vox$plr <- ifelse(vox$p02 == 20, 1, ### le parti radical democratique fusionne avec le parti liberal en 2009
                  ifelse(vox$p02 == 4, 1,
                  ifelse(is.na(vox$p02), NA, 0)))



vox$gender <- factor(vox$sexe, levels = c(1, 2), labels = c("male", "female"))
vox$annee_f <- factor(vox$annee)
vox$married <- ifelse(vox$etatciv == 2, 1,
                      ifelse(is.na(vox$etatciv), NA, 0))

vox$regionL <- as_character(vox$regiling)
vox$religion <- relevel(factor(as_character(vox$confess)), ref = "Catholique romain")

## recoding age in 4 categories


vox$age_cat <- if_else(vox$ age <= 29, 1,
                  if_else(vox$ age %>% between(30,44), 2,
                    if_else(vox$ age %>% between(45,64), 3, 
                      if_else(vox$ age >= 65, 4,
                        if_else(is.na(vox$ age), NA, NA)))))

vox$anne_f <- factor(vox$annee)

vox$canton_f <- as_character(vox$canton)

```


```{r missing value check function}
#| echo: false
#| warning: false
#| message: false
missing_values <- function(data, variable, group) { 
  
   table <- data %>% 
     group_by({{group}}) %>% 
     count({{variable}}) %>% 
     mutate(prop = n/sum(n)) %>% 
     filter(is.na({{variable}})) %>% 
     ungroup()
  
   plot <- 
     ggplot(data = table, aes(x = {{group}}, y = prop))+
     geom_col()+
     geom_label(aes(x = {{group}}, y = prop, label = {{group}}))
   
   print(plot)
  
}

```

```{r missing values plot check}
#| echo: false
#| warning: false
#| message: false
#| include: false
#| eval: false
vox %>% missing_values(variable = confess, group = annee)
vox %>% missing_values(variable = canton_f, group = annee)
```


```{r descriptive stats educ and income}
#| echo: false
#| warning: false
#| message: false
vox %>% 
  count(educ) %>% 
  mutate(prop = n/sum(n), 
         label = as_character(educ)) %>% 
  gt()


vox %>% 
  count(val11) %>% 
  mutate(prop = n/sum(n), 
         label = as_character(val11)) %>% 
  gt()
```


```{r trust in government by income group}
#| echo: false
#| warning: false
#| message: false
trust_gov_inc <- 
  vox %>% 
  group_by(annee, income) %>% 
  count(a22) %>% 
  mutate(prop = n/sum(n),
         se = sqrt(prop*(1-prop)/n),
         lower = prop - qnorm(.975)*se,
         upper = prop + qnorm(.975)*se,
         d2001 = if_else(annee >= 2001, 1, 0))%>% 
  ungroup() %>% 
  filter(a22 == 1) %>% 
  drop_na()

plot1981_2000 <- 
trust_gov_inc %>% 
  filter(annee <= 2000) %>% 
  ggplot()+
  aes(y = factor(annee), x = prop, color = factor(income), shape = factor(income))+
  geom_vline(xintercept = 0.5, alpha = 0.7, linetype = "dashed")+
  geom_line(aes(group = factor(annee)))+
  geom_point(size = 2.2)+
  scale_color_brewer(palette = "Set1")+
  scale_x_continuous(labels = scales::percent_format(accuracy = 1))+
  theme(legend.position = "none")+
  labs(x = "", y = "")

plot2001_2016 <- 
trust_gov_inc %>% 
  filter(annee > 2000) %>% 
  ggplot()+
  aes(y = factor(annee), x = prop, color = factor(income), shape = factor(income))+
  geom_vline(xintercept = 0.5, alpha = 0.7, linetype = "dashed")+
  geom_line(aes(group = factor(annee)))+
  geom_point(size = 2.2)+
  scale_color_brewer(palette = "Set1")+
  scale_x_continuous(labels = scales::percent_format(accuracy = 1))+
  labs(color = "income group", shape = "income group",
       y = "", x = "")+
  theme(legend.position = c(0.8,0.35),
        legend.background = element_blank())






title <- ggdraw() + 
  draw_label(
    "Trust in Swiss Government",
    fontface = 'bold',
    x = 0,
    hjust = 0
  ) +
  theme(
    # add margin on the left of the drawing canvas,
    # so title is aligned with left edge of first plot
    plot.margin = margin(0, 0, 0, 7)
  )

```


```{r plot grid trust gov}
#| echo: false
#| warning: false
#| message: false
plotgrid <- plot_grid(plot1981_2000, plot2001_2016)



cowplot::plot_grid(title, plotgrid, ncol = 1, rel_heights = c(0.1, 1))
```

```{r vote for the left by income group}
#| echo: false
#| warning: false
#| message: false
support_pss <- 
  vox %>% 
  group_by(annee, income) %>% 
  count(pss) %>% 
  mutate(prop = n/sum(n),
         se = sqrt(prop*(1-prop)/n),
         lower = prop - qnorm(.975)*se,
         upper = prop + qnorm(.975)*se) %>% 
  ungroup() %>% 
  filter(pss == 1) %>% 
  group_by(annee) %>% 
  mutate(mean_prop = mean(prop)) %>% 
  ungroup() %>% 
  drop_na()


supportpssplot1 <- 
support_pss %>% 
  filter(annee <= 2000) %>% 
  ggplot()+
  aes(y = factor(annee), x = prop, color = factor(income), shape = factor(income))+
  geom_line(aes(group = factor(annee)))+
  geom_point(size = 2.2)+
  scale_color_brewer(palette = "Set1")+
  scale_x_continuous(labels = scales::percent_format(accuracy = 1))+
  theme(legend.position = "none")+
  labs(x = "", y = "")

supportpssplot2 <- 
support_pss  %>% 
  filter(annee > 2000) %>% 
  ggplot()+
  aes(y = factor(annee), x = prop, color = factor(income), shape = factor(income))+
  geom_line(aes(group = factor(annee)))+
  geom_point(size = 2.2)+
  scale_color_brewer(palette = "Set1")+
  scale_x_continuous(labels = scales::percent_format(accuracy = 1))+
  labs(color = "income group", shape = "income group",
       y = "", x = "")+
  theme(legend.position = "top")



title_pss <- ggdraw() + 
  draw_label(
    "Support for Swiss Socialist Party",
    fontface = 'bold',
    x = 0,
    hjust = 0
  ) +
  theme(
    # add margin on the left of the drawing canvas,
    # so title is aligned with left edge of first plot
    plot.margin = margin(0, 0, 0, 7)
  )

plotgridpss <- plot_grid(supportpssplot1, supportpssplot2)



cowplot::plot_grid(title_pss, plotgridpss, ncol = 1, rel_heights = c(0.1, 1))

```

```{r support plr by income group}
#| echo: false
#| warning: false
#| message: false
support_plr <- 
  vox %>% 
  group_by(annee, income) %>% 
  count(plr) %>% 
  mutate(prop = n/sum(n),
         se = sqrt(prop*(1-prop)/n),
         lower = prop - qnorm(.975)*se,
         upper = prop + qnorm(.975)*se,
         d2001 = if_else(annee >= 2001, 1, 0))%>% 
  ungroup() %>% 
  filter(plr == 1) %>% 
  group_by(annee) %>% 
  mutate(mean_prop = mean(prop)) %>% 
  ungroup() %>% 
  drop_na()

supportplrplot1 <- 
support_plr %>% 
  filter(annee <= 2000) %>% 
  ggplot()+
  aes(y = factor(annee), x = prop, color = factor(income), shape = factor(income))+
  geom_line(aes(group = factor(annee)))+
  geom_point(size = 2.2)+
  scale_color_brewer(palette = "Set1")+
  scale_x_continuous(labels = scales::percent_format(accuracy = 1))+
  theme(legend.position = "none")+
  labs(x = "", y = "")

supportplrplot2 <- 
support_plr  %>% 
  filter(annee > 2000) %>% 
  ggplot()+
  aes(y = factor(annee), x = prop, color = factor(income), shape = factor(income))+
  geom_line(aes(group = factor(annee)))+
  geom_point(size = 2.2)+
  scale_color_brewer(palette = "Set1")+
  scale_x_continuous(labels = scales::percent_format(accuracy = 1))+
  labs(color = "income group", shape = "income group",
       y = "", x = "")+
  theme(legend.position = "top",
        legend.background = element_blank())






title_plr <- ggdraw() + 
  draw_label(
    "Support for radical/liberal Party",
    fontface = 'bold',
    x = 0,
    hjust = 0
  ) +
  theme(
    # add margin on the left of the drawing canvas,
    # so title is aligned with left edge of first plot
    plot.margin = margin(0, 0, 0, 7)
  )

plotgridpss <- plot_grid(supportplrplot1, supportplrplot2)



cowplot::plot_grid(title_plr, plotgridpss, ncol = 1, rel_heights = c(0.1, 1))
```

```{r support udc by income group}
#| echo: false
#| warning: false
#| message: false

support_udc <- 
  vox %>% 
  group_by(annee, income) %>% 
  count(udc) %>% 
  mutate(prop = n/sum(n),
         se = sqrt(prop*(1-prop)/n),
         lower = prop - qnorm(.975)*se,
         upper = prop + qnorm(.975)*se,
         d2001 = if_else(annee >= 2001, 1, 0))%>% 
  ungroup() %>% 
  filter(udc == 1) %>% 
  group_by(annee) %>% 
  mutate(mean_prop = mean(prop)) %>% 
  ungroup() %>% 
  drop_na()

supportudcplot1 <- 
support_udc %>% 
  filter(annee <= 2000) %>% 
  ggplot()+
  aes(y = factor(annee), x = prop, color = factor(income), shape = factor(income))+
  geom_line(aes(group = factor(annee)))+
  geom_point(size = 2.2)+
  scale_color_brewer(palette = "Set1")+
  scale_x_continuous(labels = scales::percent_format(accuracy = 1))+
  theme(legend.position = "none")+
  labs(x = "", y = "")

supportudcplot2 <- 
support_udc  %>% 
  filter(annee > 2000) %>% 
  ggplot()+
  aes(y = factor(annee), x = prop, color = factor(income), shape = factor(income))+
  geom_line(aes(group = factor(annee)))+
  geom_point(size = 2.2)+
  scale_color_brewer(palette = "Set1")+
  scale_x_continuous(labels = scales::percent_format(accuracy = 1))+
  labs(color = "income group", shape = "income group",
       y = "", x = "")+
  theme(legend.position = "top",
        legend.background = element_blank())






title_udc <- ggdraw() + 
  draw_label(
    "Support for Swiss People's Party",
    fontface = 'bold',
    x = 0,
    hjust = 0
  ) +
  theme(
    # add margin on the left of the drawing canvas,
    # so title is aligned with left edge of first plot
    plot.margin = margin(0, 0, 0, 7)
  )

plotgridpss <- plot_grid(supportudcplot1, supportudcplot2)



cowplot::plot_grid(title_udc, plotgridpss, ncol = 1, rel_heights = c(0.1, 1))


```



```{r no pooling repeated cross section (nprcs) regression vote for ssp}
nprcs_ssp <- 
vox %>%
  split(.$annee_f) %>% 
  map(~ glm(pss ~ income + educ, data = .x, family = binomial(link = "logit")))

year <- data.frame(year = 1981:2016)


nprcs_ssp %>% 
  map_df(tidy) %>% 
  mutate(year = year[rep(seq_len(nrow(year)), each = 3),],
         test = if_else(p.value <= 0.05, TRUE, FALSE),
         lower = estimate - 1.96*std.error,
         upper = estimate + 1.96*std.error) -> nprcs_ssp_results


nprcs_ssp_results %>% 
  filter(term != "(Intercept)") %>% 
  ggplot()+
  aes(x = estimate, y = factor(year), group = term, color = term)+
  geom_vline(xintercept = 0, linetype = "dashed")+
  geom_pointrange(aes(xmin = lower, xmax = upper))+
  facet_wrap(~term)+
  labs(title = "Vote for SSP, log(odds)")

```


```{r average marginal effect nprcs ssp}
# computing average marginal effect for each year
ame_income_nprcrs_ssp <- 
nprcs_ssp %>% 
  map(~slopes(.x ,variables = "income")) %>% 
  map_df(~summarise(.x, ame = mean(estimate),
            high = mean(conf.high),
            low = mean(conf.low))) %>% 
           mutate(year = 1981:2016,
                  variable = "income")

ame_educ_nprcrs_ssp <- 
nprcs_ssp %>% 
  map(~slopes(.x ,variables = "educ")) %>% 
  map_df(~summarise(.x, ame = mean(estimate),
            high = mean(conf.high),
            low = mean(conf.low))) %>% 
           mutate(year = 1981:2016, 
                  variable = "educ")


ame_nprcrs_ssp <- rbind(ame_income_nprcrs_ssp, ame_educ_nprcrs_ssp)
```



```{r function for nprcrs}
nprcrs_ame <- function(regression, variable, sequence){

ame <- 
regression %>% 
  map(~slopes(.x ,variables = {{variable}})) %>% 
  map_df(~summarise(.x, ame = mean(estimate),
            high = mean(conf.high),
            low = mean(conf.low))) %>% 
           mutate(year = {{sequence}},
                  variable = {{variable}})


print(ame)

}
```


```{r plot ame nprcs ssp}
plot_ame_ssp <- 
ame_nprcrs_ssp %>% 
  ggplot()+
  aes(y = ame, x = year, color = variable, shape = variable)+
  geom_hline(yintercept = 0, linetype = "dashed")+
  geom_point()+
  geom_line()+
  geom_pointrange(aes(ymin = low, ymax = high))+
  scale_y_continuous(labels = scales::percent_format())+
  labs(title = "Probability to vote for SSP",
       subtitle = "Repeated cross-section",
       y = "", x = "Average Marginal Effect")
plot_ame_ssp
```


```{r nprcs ssp with controls}




nprcs_ssp_controls <- 
vox %>%
  split(.$annee_f) %>% 
  map(~ glm(pss ~ income + educ + gender + age_cat + married + regionL + religion, data = .x, family = binomial(link = "logit")))

nprcs_ssp_controls_results <- 
nprcs_ssp_controls %>% 
  map_df(tidy) %>% 
  mutate(
         test = if_else(p.value <= 0.05, TRUE, FALSE),
         lower = estimate - 1.96*std.error,
         upper = estimate + 1.96*std.error)


ame_income_nprcs_ssp_controls <- 
nprcs_ssp_controls %>% 
  map(~slopes(.x ,variables = "income")) %>% 
  map_df(~summarise(.x, ame = mean(estimate),
            high = mean(conf.high),
            low = mean(conf.low))) %>% 
           mutate(year = 1981:2016,
                  variable = "income")

ame_education_nprcs_ssp_controls <- 
nprcs_ssp_controls %>% 
  map(~slopes(.x ,variables = "educ")) %>% 
  map_df(~summarise(.x, ame = mean(estimate),
            high = mean(conf.high),
            low = mean(conf.low))) %>% 
           mutate(year = 1981:2016,
                  variable = "educ")


ame_nprcs_ssp_controls <- rbind(ame_income_nprcs_ssp_controls, ame_education_nprcs_ssp_controls)

```


```{r plot ame ssp full}

plot_ame_nprcs_ssp_controls <- 
ame_nprcs_ssp_controls %>% 
  ggplot()+
  aes(y = ame, x = year, color = variable, shape = variable)+
  geom_hline(yintercept = 0, linetype = "dashed")+
  geom_point()+
  geom_line()+
  geom_pointrange(aes(ymin = low, ymax = high))+
  scale_y_continuous(labels = scales::percent_format())+
  labs(title = "Probability to vote for SSP",
       subtitle = "No pooling model, after controls",
       y = "", x = "Average Marginal Effect")

plot_ame_nprcs_ssp_controls
```





```{r svp nprcs}
#| echo: false
#| message: false
#| warning: false
nprcs_udc <- 
vox %>%
  split(.$annee_f) %>% 
  map(~ glm(udc ~ income + educ, data = .x, family = binomial(link = "logit")))

year <- data.frame(year = 1981:2016)

nprcs_udc_results_udc <- 
nprcs_udc %>% 
  map_df(tidy) %>% 
  mutate(year = year[rep(seq_len(nrow(year)), each = 3),],
         test = if_else(p.value <= 0.05, TRUE, FALSE),
         lower = estimate - 1.96*std.error,
         upper = estimate + 1.96*std.error)

```


```{r nprcs udc ame}
#| echo: false
#| message: false
#| warning: false
# computing average marginal effect for each year
ame_nprcs_income_udc <- 
nprcs_udc %>% 
  map(~slopes(.x ,variables = "income")) %>% 
  map_df(~summarise(.x, ame = mean(estimate),
            high = mean(conf.high),
            low = mean(conf.low))) %>% 
           mutate(year = 1981:2016,
                  variable = "income")

ame_nprcs_educ_udc <- 
nprcs_udc %>% 
  map(~slopes(.x ,variables = "educ")) %>% 
  map_df(~summarise(.x, ame = mean(estimate),
            high = mean(conf.high),
            low = mean(conf.low))) %>% 
           mutate(year = 1981:2016, 
                  variable = "educ")


ame_nprcs_udc <- rbind(ame_nprcs_income_udc, ame_nprcs_educ_udc)

```

```{r svp plot}
#| echo: false
#| message: false
#| warning: false
ame_nprcs_udc %>% 
  ggplot()+
  aes(y = ame, x = year, color = variable, shape = variable)+
  geom_hline(yintercept = 0, linetype = "dashed")+
  geom_point()+
  geom_line()+
  geom_pointrange(aes(ymin = low, ymax = high))+
  scale_y_continuous(labels = scales::percent_format())+
  labs(title = "Probability to vote for SVP",
       subtitle = "No pooling model, repeated cross-sectional logit regression",
       y = "", x = "Average Marginal Effect")
```


```{r svp nprcs controls}
#| echo: false
#| message: false
#| warning: false
nprcs_udc_controls <- 
vox %>%
  split(.$annee_f) %>% 
  map(~ glm(udc ~ income + educ + gender + age_cat + married + regionL + religion, data = .x, family = binomial(link = "logit")))



ame_nprcs_income_udc_controls <- 
nprcs_udc_controls %>% 
  map(~slopes(.x ,variables = "income")) %>% 
  map_df(~summarise(.x, ame = mean(estimate),
            high = mean(conf.high),
            low = mean(conf.low))) %>% 
           mutate(year = 1981:2016,
                  variable = "income")

ame_nprcs_educ_udc_controls <- 
nprcs_udc_controls %>% 
  map(~slopes(.x ,variables = "educ")) %>% 
  map_df(~summarise(.x, ame = mean(estimate),
            high = mean(conf.high),
            low = mean(conf.low))) %>% 
           mutate(year = 1981:2016, 
                  variable = "educ")


ame_nprcs_udc_controls <- rbind(ame_nprcs_income_udc_controls, ame_nprcs_educ_udc_controls)


ame_nprcs_udc_controls %>% 
  ggplot()+
  aes(y = ame, x = year, color = variable, shape = variable)+
  geom_hline(yintercept = 0, linetype = "dashed")+
  geom_point()+
  geom_line()+
  geom_pointrange(aes(ymin = low, ymax = high))+
  scale_y_continuous(labels = scales::percent_format())+
  labs(title = "Probability to vote for SVP",
       subtitle = "No pooling model, repeated cross-sectional logit regression after controls",
       y = "", x = "Average Marginal Effect")
```

```{r plr nprcs controls}
#| echo: false
#| message: false
#| warning: false
nprcs_plr_controls <- 
vox %>%
  split(.$annee_f) %>% 
  map(~ glm(plr ~ income + educ + gender + age_cat + married + regionL + religion, data = .x, family = binomial(link = "logit")))



ame_nprcs_income_plr_controls <- 
nprcs_plr_controls %>% 
  map(~slopes(.x ,variables = "income")) %>% 
  map_df(~summarise(.x, ame = mean(estimate),
            high = mean(conf.high),
            low = mean(conf.low))) %>% 
           mutate(year = 1981:2016,
                  variable = "income")

ame_nprcs_educ_plr_controls <- 
nprcs_plr_controls %>% 
  map(~slopes(.x ,variables = "educ")) %>% 
  map_df(~summarise(.x, ame = mean(estimate),
            high = mean(conf.high),
            low = mean(conf.low))) %>% 
           mutate(year = 1981:2016, 
                  variable = "educ")


ame_nprcs_plr_controls <- rbind(ame_nprcs_income_plr_controls, ame_nprcs_educ_plr_controls)


ame_nprcs_plr_controls %>% 
  ggplot()+
  aes(y = ame, x = year, color = variable, shape = variable)+
  geom_hline(yintercept = 0, linetype = "dashed")+
  geom_point()+
  geom_line()+
  geom_pointrange(aes(ymin = low, ymax = high))+
  scale_y_continuous(labels = scales::percent_format())+
  labs(title = "Probability to vote for radical/liberal party",
       subtitle = "No pooling model, repeated cross-sectional logit regression after controls",
       y = "", x = "Average Marginal Effect")
```





### Partial pooling for year

```{r partial pooling canton pss}
glmer_pss <- glmer(data = vox,
                   formula = pss ~ income + educ + gender + age_cat + married + regionL + religion + (income + educ | annee_f),
                   family = binomial(link = "logit"))
```

```{r function ame}

## function to simplify the code
# table ame is for computing the average marginal effect
table_ame <- function(variable, regression, group){
  
glmer_table <- slopes({{regression}}, variables = {{variable}})


ame <- 
 glmer_table  %>% 
  group_by({{group}}) %>% 
  summarise(ame = mean(estimate),
            high = mean(conf.high),
            low = mean(conf.low)) %>% 
  ungroup() %>% 
  mutate(variable = {{variable}})

print(ame)

}
```

```{r ame partial pooling pss}
#| echo: false
#| message: false
#| warning: false
ame_glmer_pss_inc <- table_ame(regression = glmer_pss, group = annee_f, variable = "income")
ame_glmer_pss_educ <- table_ame(regression = glmer_pss, group = annee_f, variable = "educ")

ame_glmer_pss_full <- rbind(ame_glmer_pss_inc, ame_glmer_pss_educ)
  
```

```{r plot ame partial pooling pss}
#| echo: false
#| message: false
#| warning: false
plot_ame_glmer_ssp <- 
ame_glmer_pss_full %>% 
  ggplot()+
  aes(y = ame, x = annee_f, color = variable, shape = variable, group = variable)+
  geom_hline(yintercept = 0, linetype = "dashed")+
  geom_point()+
  geom_line()+
  geom_pointrange(aes(ymin = low, ymax = high))+
  scale_y_continuous(labels = scales::percent_format())+
  labs(title = "Probability to vote for SSP",
       subtitle = "Partial Pooling (glmer) model",
       y = "", x = "Average Marginal Effect")+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

plot_ame_nprcs_ssp_controls
plot_ame_glmer_ssp
```


```{r partial pooling plr}
glmer_plr <- glmer(data = vox,
                   formula = plr ~ income + educ + gender + age_cat + married + regionL + religion + (income + educ | annee_f),
                   family = binomial(link = "logit"))
```



```{r}
#| echo: false
#| message: false
#| warning: false
glmer_plr_income <- table_ame(regression = glmer_plr, variable = "income", group = annee_f)
glmer_plr_educ <- table_ame(regression = glmer_plr, variable = "educ", group = annee_f)
ame_glmer_plr <- rbind(glmer_plr_educ, glmer_plr_income)
```





```{r}
#| echo: false
#| message: false
#| warning: false
plot_ame_glmer_plr <- 
ame_glmer_plr %>% 
  ggplot()+
  aes(y = ame, x = annee_f, color = variable, shape = variable, group = variable)+
  geom_hline(yintercept = 0, linetype = "dashed")+
  geom_point()+
  geom_line()+
  geom_pointrange(aes(ymin = low, ymax = high))+
  scale_y_continuous(labels = scales::percent_format())+
  labs(title = "Probability to vote for PLR",
       subtitle = "Partial Pooling (glmer) model",
       y = "", x = "Average Marginal Effect")+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))


plot_ame_glmer_plr
```












